[package]
name = "noac"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.13", features = ["csr"] }
wasm-logger = "0.2.0"

[dev-dependencies]
wasm-bindgen-test = "0.2"
